FROM node:14-slim

WORKDIR /usr/src/app

COPY ./package.json /.
COPY ./package-lock.json /.

RUN npm install
RUN npm install express cors mongoose bcrypt jsonwebtoken

COPY . .

EXPOSE 5000

CMD [ "node", "index.js" ]